services:
  www:
    build: docker/php
    container_name: studi_symfony_php
    ports:
      - 8088:80
    volumes:
      - ./:/var/www
      - ./docker/php/vhosts:/etc/apacche2/site-enabled
    networks:
      - studi_symfony
#pour comuniquer avec nos diff√©rents composants

  mysql:
    image: mysql
    container_name: studi_symfony_mysql
    volumes:
      - ./var/db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: ABCD1234!
    networks:
      - studi_symfony

  phpmyadmin:
    image: aphpmyadmin
    container_name: studi_symfony_phpmyadmin
    ports:
      - 8089:80
    networks:
      - studi_symfony

networks:
  studi_symfony:

